### ISSUE TITLE
TypeError on startup

### ISSUE THREAD

**Issue by chebarash** [Aloento/FFmpeg4JS#3]
![image](https://user-images.githubusercontent.com/64980797/156400818-0827e69e-6973-412f-b366-3fcea40df9b3.png)

**Comment by Aloento** [comment]
could you give me an example for your use case?

**Comment by chebarash** [comment]
`const ffmpeg = require("ffmpeg4js");

const data = new Uint8Array(fs.readFileSync("wacker.mp4"));

const result = ffmpeg({
  MEMFS: [{ name: "wacker.mp4", data }],
  arguments: [
    "-i",
    "wacker.mp4",
    `-vf`,
    `scale=512:512`,
    `-t`,
    `00:00:03`,
    `-r`,
    `30`,
    `-fs`,
    `256k`,
    `-c:v`,
    `libvpx-vp9`,
    `-map_metadata`,
    `-1`,
    `-an`,
    "wacker.webm",
  ],
});

console.log(result);`

**Comment by chebarash** [comment]
`const ffmpeg = require("ffmpeg4js");

const data = new Uint8Array(fs.readFileSync("wacker.mp4"));

const result = ffmpeg({
  MEMFS: [{ name: "wacker.mp4", data }],
  arguments: [
    "-i",
    "wacker.mp4",
    "-vf",
    "scale=512:512",
    "-t",
    "00:00:03",
    "-r",
    "30",
    "-fs",
    "256k",
    "-c:v",
    "libvpx-vp9",
    "-map_metadata",
    "-1",
    "-an",
    "wacker.webm",
  ],
});

console.log(result);`

**Comment by chebarash** [comment]
`const ffmpeg = require("ffmpeg4js");

const data = new Uint8Array(fs.readFileSync("wacker.mp4"));

const result = ffmpeg({
  MEMFS: [{ name: "wacker.mp4", data }],
  arguments: [
    "-i",
    "wacker.mp4",
    "-vf",
    "scale=512:512",
    "-t",
    "00:00:03",
    "-r",
    "30",
    "-fs",
    "256k",
    "-c:v",
    "libvpx-vp9",
    "-map_metadata",
    "-1",
    "-an",
    "wacker.webm",
  ],
});

console.log(result);`

**Comment by chebarash** [comment]
`const ffmpeg = require("ffmpeg4js");

const data = new Uint8Array(fs.readFileSync("wacker.mp4"));

const result = ffmpeg({
  MEMFS: [{ name: "wacker.mp4", data }],
  arguments: [
    "-i",
    "wacker.mp4",
    "-vf",
    "scale=512:512",
    "-t",
    "00:00:03",
    "-r",
    "30",
    "-fs",
    "256k",
    "-c:v",
    "libvpx-vp9",
    "-map_metadata",
    "-1",
    "-an",
    "wacker.webm",
  ],
});

console.log(result);`

**Comment by chebarash** [comment]
`const ffmpeg = require("ffmpeg4js");`

`const data = new Uint8Array(fs.readFileSync("wacker.mp4"));`

`const result = ffmpeg({
  MEMFS: [{ name: "wacker.mp4", data }],
  arguments: [
    "-i",
    "wacker.mp4",
    "-vf",
    "scale=512:512",
    "-t",
    "00:00:03",
    "-r",
    "30",
    "-fs",
    "256k",
    "-c:v",
    "libvpx-vp9",
    "-map_metadata",
    "-1",
    "-an",
    "wacker.webm",
  ],
});`

`console.log(result);`

**Comment by Aloento** [comment]
Sync run current Not Supported
please `new Worker()` and it's also working for Nodejs.
https://github.com/Aloento/FFmpeg4JS#via-web-worker

**Comment by chebarash** [comment]
> Sync run current Not Supported please `new Worker()` and it's also working for Nodejs. https://github.com/Aloento/FFmpeg4JS#via-web-worker

Do you plan to add sync?

**Comment by Aloento** [comment]
yes, but not now.
anyway, it's very easy to add: https://github.com/Aloento/FFmpeg4JS/blob/8a0b45143c65541bba5e1747d46703944aedc0a6/Makefile#L146-L149
