### ISSUE TITLE
小白请问下，压缩视频这个命令报错

### ISSUE THREAD

**Issue by NotGeekAtAll** [Aloento/FFmpeg4JS#4]
使用如下命令
```
const res = await ff(Comlink.transfer([{ name, data }], [data]), {
    arguments: ['-i', name, '-ss', '0', '-to', '5', '-fs', '8M', 'out.mp4'],
  });
```
报错
![image](https://user-images.githubusercontent.com/16792509/219999748-81a48530-8bd6-48b2-8b64-4c3eb5880069.png)

**Comment by Aloento** [comment]
这种情况你手动指定一下输出格式就好了
具体还得搜一下ffmepg指定输出格式的办法
